### ISSUE TITLE
Use the _W versions of the Windows API, especially for SEC_WINNT_AUTH_IDENTITY

### ISSUE THREAD

**Issue by schlenk** [mongodb-labs/winkerberos#1]
It would be much prefered if you used the _W versions of the API, especially for the  auth identify.

Both usernames and credentials/passwords might contain UTF-16 chars outside of the current codepage.

In addition, your code reacts in funny ways if one changes the current user local (e.g. when using remote desktop, try switching between turkish, german and EN_US and use some umlauts or accents in the usernames or passwords, those might get silently converted).

Its close to trivial to use the UTF-16 APIs from python thanks to the usual unicode support.

**Comment by behackett** [comment]
This was already on my list of things to do. It should be fairly easy using Tchar.h and python's support for wchar_t.

https://msdn.microsoft.com/en-us/library/c426s321.aspx

**Comment by behackett** [comment]
This should be resolved now. It took quite a bit of effort since PyArg_ParseTuple is useless for getting byte strings as wchar_t in python2.x.
