### ISSUE TITLE
Use CryptBinaryToString() for base64 instead of Apple's base64.c

### ISSUE THREAD

**Issue by schlenk** [mongodb-labs/winkerberos#2]
https://msdn.microsoft.com/en-us/library/windows/desktop/aa379887%28v=vs.85%29.aspx

You probably load crypt32.dll anyway via the SSPI stuff.

**Comment by behackett** [comment]
That's an interesting idea, thanks for the link. It would be nice to get rid of Apple's base64 library.

**Comment by behackett** [comment]
See also CryptStringToBinary()

https://msdn.microsoft.com/en-us/library/windows/desktop/aa380285(v=vs.85).aspx

**Comment by behackett** [comment]
It looks like you have to explicitly link against Crypt32.lib for this to work. secur32.lib isn't enough.
