### ISSUE TITLE
support building with mingw

### ISSUE THREAD

**Issue by totaam** [mongodb-labs/winkerberos#21]
Please consider applying the patch below to support building winkerberos with mingw:
[mingw build patch](http://xpra.org/trac/attachment/ticket/1691/winkerberos-mingw.patch)

**Comment by behackett** [comment]
Thanks for working on this patch. I have a few questions.

- Why do you have to check an environment variable for find mingw? Python's distutils should be able to find it automatically. For example, "python setup.py build_ext -c mingw64".
- I'm guessing you are using Mingw-w64? 
- I'm also just curious why you are building WinKerberos from source? There are pre-built wheels on pypi.

**Comment by totaam** [comment]
- IIRC there is a more "correct" way of detecting a mingw build, but I can't remember what it is
- yes, mingw-w64
- re: "why build from source", mostly personal preference: if we can't build something from source, we tend to not trust our ability to maintain a working system in the long run - pypi wheels are great, but being able to modify the source and rebuild (for debugging or whatever) - or being able to use the same compiler (gcc vs msvc) - all those things matter to us

**Comment by behackett** [comment]
Would you like to send a pull request that I can review and merge? If not, I can copy from the link you provided.

**Comment by behackett** [comment]
This was resolved by #22
