### ISSUE TITLE
installing error in windows

### ISSUE THREAD

**Issue by alirezaimi** [mongodb-labs/winkerberos#23]
Hi
I can not install this package in windows(sever 2012 r2) :
Python 3.7.0 .

	PS C:\Windows\system32> pip install winkerberos -U
	Collecting winkerberos
	  Using cached https://files.pythonhosted.org/packages/85/b2/c5a66595bb477f1939596d80fa308e357c28abe22d3d6ce6cc2208c324e
	e/winkerberos-0.7.0.zip
	Installing collected packages: winkerberos
	  Running setup.py install for winkerberos ... error
		Complete output from command c:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\dvp7\\AppD
	ata\\Local\\Temp\\pip-install-j8xs4qt6\\winkerberos\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read()
	.replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\dvp7\AppData\Local\Tem
	p\pip-record-jjpe1tk4\install-record.txt --single-version-externally-managed --compile:
		running install
		running build
		running build_ext
		building 'winkerberos' extension
		error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.
	0\\VC\\PlatformSDK\\lib'

**Comment by behackett** [comment]
What version of Python are you using?

**Comment by alirezaimi** [comment]
@behackett Edit original post .(Python 3.7.0)

**Comment by behackett** [comment]
I've uploaded wheels for 32 and 64 bit Python 3.7 to pypi. You should be able to install with no issues now. Sorry about that.

The issue you are having is that WinKerberos is written in pure C (no actual Python). Installing requires Microsoft's Visual C++ compiler. The wheels I just uploaded are pre-compiled binaries.
