### ISSUE TITLE
Spelling mistake in function name

### ISSUE THREAD

**Issue by gr-harryc** [mongodb-labs/winkerberos#25]
Comparing these two functions:
https://github.com/apple/ccs-pykerberos/blob/master/src/kerberos.c#L385
https://github.com/mongodb-labs/winkerberos/blob/master/src/winkerberos.c#L739

it looks like this implementation's `authGSSClientUsername` should be spelled `authGSSClientUserName`

**Comment by behackett** [comment]
Thanks for pointing this out. I'll fix it in the next release. Luckily we're still pre-1.0 so I think it's safe to make a minor breaking change.
