### ISSUE TITLE
Use SecureZeroMemory() to zero out the copied password

### ISSUE THREAD

**Issue by schlenk** [mongodb-labs/winkerberos#3]
Might be a good idea to zero out the password after using it in AcquireCredentialsHandleA(). Doesn't help a lot with Pythons String objects, but its better than nothing.

**Comment by behackett** [comment]
Well, we're not using a copy of the string, just the pointer returned by PyArg_ParseTupleAndKeywords, so we can't free the memory. A copy doesn't seem necessary.

**Comment by schlenk** [comment]
True. Missed that part, as there are some variants that create a copy.

Might be a good idea to use z# or z* though for the PyArg_ParseTupleAndKeywords, to allow any buffer object (and possibly avoid leaking passwords into PyString objects, e.g. if you write your own buffer api compatible object type).

**Comment by behackett** [comment]
That's a great idea. Can you open a separate ticket documenting the use case?

**Comment by behackett** [comment]
This became relevant again with the change for #1.

**Comment by behackett** [comment]
Also resolved in 3476f7c734307f4715eb5838eede919ecd41d8cb
