### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by ofek** [mongodb-labs/winkerberos#36]
Hello! Are there plans to ship binary wheels for Python 3.8 soon? Many of us would really appreciate it.

Thanks 😄 

cc @behackett

**Comment by behackett** [comment]
Thanks for the gentle nudge. I'll get it done this week.

**Comment by ofek** [comment]
Thank you!

**Comment by behackett** [comment]
Sorry for the really long wait on this. I've uploaded Python 3.8 builds of 0.7.0 for 64 and 32 bit architectures.

**Comment by ofek** [comment]
Thanks!!!
